development:
  secret_key_base: <%= ENV['SECRET_KEY'] %>

test:
  secret_key_base: <%= ENV['SECRET_KEY'] %>

staging:
  secret_key_base: <%= ENV['SECRET_KEY'] %>

production:
  secret_key_base: <%= ENV['SECRET_KEY'] %>
